/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorial: [{ type: 'autogenerated', dirName: 'tutorial' }],
  library: [{ type: 'autogenerated', dirName: 'library' }],
  mod: [{ type: 'autogenerated', dirName: 'mod' }],
  tool: [{ type: 'autogenerated', dirName: 'tool' }],
};

export default sidebars;
